config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
     collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  root 'blogs#index'

  if Rails.env.development?
      mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :content, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
   if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
   end
  end

  def create
   @contact = Contact.new(contacts_params)
    if @contact.save
      redirect_to root_path, notice: "お問い合わせが完了しました！"
      NoticeMailer.sendmail_contact(@contact).deliver
    else
      # 入力フォームを再描画します。
      render action: 'new'
    end
  end

  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
  end

  private
   def contacts_params
     params.require(:contact).permit(:name, :email, :content)
   end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
  <div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
   <%= f.hidden_field :content %>

  <!-- @contact.titleと@contact.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>名前:<%= @contact.name %></p>
  <p>email:<%= @contact.email %></p>
  <p>内容:<%= @contact.content %></p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

 </div>
 </div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p id="notice"><%= notice %></p>

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
    <%= f.error_messages! %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>

  </div>
</div>